# Generated by Django 5.0.1 on 2024-01-09 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('mrp', models.FloatField()),
                ('discount_percent', models.FloatField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=500)),
                ('delete_status', models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1)),
            ],
        ),
    ]
