# Generated by Django 5.0.1 on 2024-01-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='special_category',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'New Arrival'), (2, 'Great Discount'), (3, 'Flash Sale'), (4, 'Featured Product')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=models.SET('Others'), related_name='products', to='products.category'),
        ),
    ]
