# Generated by Django 5.0.3 on 2024-04-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_size_remove_product_special_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='age_limit',
            field=models.CharField(blank=True, default='Not Given !'),
        ),
    ]
